# Generated by Django 5.0.4 on 2024-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_imovel_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
    ]
