# Generated by Django 5.0.4 on 2024-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino'), (3, 'Não Informar')])),
            ],
        ),
    ]
