# Generated by Django 5.0.4 on 2024-04-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('resumo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
                ('oferta_venda', models.BooleanField(default=False)),
                ('oferta_locacao', models.BooleanField(default=False)),
            ],
        ),
    ]
