# Generated by Django 5.0.4 on 2024-05-21 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('resumo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=300)),
                ('oferta_venda', models.BooleanField(default=False)),
                ('oferta_locacao', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=False)),
                ('foto_capa', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('link_contato', models.CharField(max_length=100)),
                ('contato', models.TextField(max_length=300)),
                ('cidade', models.CharField(choices=[(3506003, 'Bauru'), (3506003, 'Botucatu'), (3526803, 'Lençóis Paulista')], default='', max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('coordenas_geograficas', models.CharField(max_length=100, null=True)),
                ('categoria', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Chácara', 'Chácara'), ('Pensão', 'Pensão'), ('Salão de Festas', 'Salão de Festas')], default='', max_length=100)),
                ('valor_locacao', models.FloatField(null=True)),
                ('valor_venda', models.FloatField(null=True)),
                ('quantidade_quartos', models.IntegerField(null=True)),
                ('quantidade_suites', models.IntegerField(null=True)),
                ('quantidade_banheiros', models.IntegerField(null=True)),
                ('quantidade_vagas_carros', models.IntegerField(null=True)),
                ('metragem_imovel', models.IntegerField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
