# Generated by Django 5.0.4 on 2024-05-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_rename_contato_imovel_informacoes_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='metragem_imovel',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_banheiros',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_quartos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_suites',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_vagas_garagem',
            field=models.FloatField(null=True),
        ),
    ]
