# Generated by Django 5.0.4 on 2024-05-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imovel_metragem_imovel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(choices=[('3506003', 'Bauru'), ('3506003', 'Botucatu'), ('3526803', 'Lençóis Paulista')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='metragem_imovel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_banheiros',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_quartos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_suites',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quantidade_vagas_garagem',
            field=models.IntegerField(null=True),
        ),
    ]
