# Generated by Django 5.0.4 on 2024-05-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_alter_imovel_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('cep', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=25)),
                ('complemento', models.CharField(max_length=25)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('finalidade', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=25)),
                ('valor_venda', models.FloatField(max_length=25)),
                ('valor_locacao', models.FloatField(max_length=25)),
                ('qtd_quartos', models.IntegerField()),
                ('qtd_suites', models.IntegerField()),
                ('qtd_banheiros', models.IntegerField()),
                ('qtd_vagas', models.IntegerField()),
                ('obs', models.TextField()),
                ('imagem_imovel', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='atualiza_dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=12)),
                ('data_nasc', models.DateField(max_length=25)),
                ('cpf_cnpj', models.CharField(max_length=25)),
                ('cep', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=25)),
                ('bairro', models.CharField(max_length=25)),
                ('numero', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=10)),
                ('confirme_senha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('DF', 'Distrito Federal'), ('MG', 'Minas Gerais')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=12)),
                ('observacao', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='detalhe_imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.CharField(max_length=25)),
                ('valor_aluguel', models.CharField(max_length=25)),
                ('condominio', models.CharField(max_length=25)),
                ('tipo_imovel', models.CharField(max_length=25)),
                ('qtd_quartos', models.CharField(max_length=25)),
                ('qtd_banheiros', models.CharField(max_length=25)),
                ('qtd_vagas', models.CharField(max_length=25)),
                ('metragem', models.CharField(max_length=25)),
                ('descrição', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='meus_imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade_imovel', models.IntegerField(choices=[(1, 'Comprar'), (2, 'Alugar')])),
                ('tipo_imovel', models.IntegerField(choices=[(1, 'Casa'), (2, 'Apartamento'), (3, 'Kit-net'), (4, 'Quarto')])),
                ('bairro', models.IntegerField(choices=[(1, 'Cecap'), (2, 'Ubirama'), (3, 'Itamaraty'), (4, 'Principe'), (4, 'Cruzeiro'), (4, 'Caju'), (4, 'Antonieta')])),
                ('imagem_imovel', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='recuperar_senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='imoveis.categoria'),
        ),
    ]
