# Generated by Django 5.0.4 on 2024-05-19 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_alter_imovel_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
