# Generated by Django 5.0.4 on 2024-05-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_delete_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='foto_capa',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
